#set_property PACKAGE_PIN M27 [get_ports dummy_out]
#set_property IOSTANDARD LVCMOS18 [get_ports dummy_out]

#set_property PACKAGE_PIN K27 [get_ports LhcClkInP]
#set_property IOSTANDARD LVDS [get_ports LhcClkInP]
#set_property IOSTANDARD LVDS [get_ports LhcClkInN]
#set_property PACKAGE_PIN BD29 [get_ports TTC_BroadcastP]
#set_property PACKAGE_PIN BB30 [get_ports TTC_BunchChounterResetP]
#set_property PACKAGE_PIN BC28 [get_ports TTC_ReadRequestP]
#set_property IOSTANDARD LVDS [get_ports TTC_BroadcastP]
#set_property IOSTANDARD LVDS [get_ports TTC_BroadcastN]
#set_property IOSTANDARD LVDS [get_ports TTC_BunchChounterResetP]
#set_property IOSTANDARD LVDS [get_ports TTC_BunchChounterResetN]
#set_property IOSTANDARD LVDS [get_ports TTC_ReadRequestP]


set_property PACKAGE_PIN BD29 [get_ports {CTRLBUS_P[0] }]
set_property PACKAGE_PIN BB30 [get_ports {CTRLBUS_P[1] }]
set_property PACKAGE_PIN BC28 [get_ports {CTRLBUS_P[2] }]
set_property PACKAGE_PIN BA29 [get_ports {CTRLBUS_P[3] }]
set_property PACKAGE_PIN AW29 [get_ports {CTRLBUS_P[4] }]
set_property PACKAGE_PIN AW27 [get_ports {CTRLBUS_P[5] }]
set_property PACKAGE_PIN AY31 [get_ports {CTRLBUS_P[6] }]
set_property PACKAGE_PIN AY28 [get_ports {CTRLBUS_P[7] }]
#set_property PACKAGE_PIN AW30 [get_ports {CTRLBUS_P[8] }]
#set_property PACKAGE_PIN AV27 [get_ports {CTRLBUS_P[9] }]
#set_property PACKAGE_PIN AU30 [get_ports {CTRLBUS_P[10]}]
##set_property PACKAGE_PIN AU28  [get_ports {CTRLBUS_P_IN}]
#set_property PACKAGE_PIN AU28 [get_ports {CTRLBUS_P[11]}]
#set_property PACKAGE_PIN AT28 [get_ports {CTRLBUS_P[12]}]
#set_property PACKAGE_PIN AP29 [get_ports {CTRLBUS_P[13]}]
#set_property PACKAGE_PIN AR28 [get_ports {CTRLBUS_P[14]}]
#set_property PACKAGE_PIN AN28 [get_ports {CTRLBUS_P[15]}]
#set_property PACKAGE_PIN AM30 [get_ports {CTRLBUS_P[16]}]
#set_property PACKAGE_PIN AK27 [get_ports {CTRLBUS_P[17]}]
#set_property PACKAGE_PIN AM27 [get_ports {CTRLBUS_P[18]}]
#set_property PACKAGE_PIN AJ29 [get_ports {CTRLBUS_P[19]}]

set_property PACKAGE_PIN AL28 [get_ports {CTRLBUS_P_IN }]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P_IN }]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_N_IN }]


set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[0]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[1]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[2]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[3]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[4]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[5]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[6]}]
set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[7]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[8]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[9]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[10]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P_IN}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[11]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[12]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[13]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[14]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[15]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[16]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[17]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[18]}]
#set_property IOSTANDARD LVDS  [get_ports {CTRLBUS_P[19]}]



set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[0]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[1]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[2]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[3]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[4]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[5]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[6]}] 
set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[7]}] 
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[8]}] 
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[9]}] 
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[10]}]
##set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N_IN}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[11]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[12]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[13]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[14]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[15]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[16]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[17]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[18]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N[19]}]
#set_property IOSTANDARD LVDS [get_ports {CTRLBUS_N_IN}]

#set_property PACKAGE_PIN  BD30 [get_ports {CTRLBUS_N[0]}] 
#set_property PACKAGE_PIN  BC30 [get_ports {CTRLBUS_N[1]}] 
#set_property PACKAGE_PIN  BC29 [get_ports {CTRLBUS_N[2]}] 
#set_property PACKAGE_PIN  BA30 [get_ports {CTRLBUS_N[3]}] 
#set_property PACKAGE_PIN  AY29 [get_ports {CTRLBUS_N[4]}] 
#set_property PACKAGE_PIN  AY27 [get_ports {CTRLBUS_N[5]}] 
#set_property PACKAGE_PIN  BA31 [get_ports {CTRLBUS_N[6]}] 
#set_property PACKAGE_PIN  BA28 [get_ports {CTRLBUS_N[7]}] 
##set_property PACKAGE_PIN  AW31 [get_ports {CTRLBUS_N[8]}] 
##set_property PACKAGE_PIN  AV28 [get_ports {CTRLBUS_N[9]}] 
##set_property PACKAGE_PIN  AV30 [get_ports {CTRLBUS_N[10]}]
###set_property PACKAGE_PINS AV29  [get_ports {CTRLBUS_N_IN}]
#set_property PACKAGE_PIN  AV29 [get_ports {CTRLBUS_N[11]}]
#set_property PACKAGE_PIN  AT29 [get_ports {CTRLBUS_N[12]}]
#set_property PACKAGE_PIN  AP30 [get_ports {CTRLBUS_N[13]}]
#set_property PACKAGE_PIN  AR29 [get_ports {CTRLBUS_N[14]}]
#set_property PACKAGE_PIN  AN29 [get_ports {CTRLBUS_N[15]}]
#set_property PACKAGE_PIN  AN30 [get_ports {CTRLBUS_N[16]}]
#set_property PACKAGE_PIN  AK28 [get_ports {CTRLBUS_N[17]}]
#set_property PACKAGE_PIN  AM28 [get_ports {CTRLBUS_N[18]}]
#set_property PACKAGE_PIN  AK29 [get_ports {CTRLBUS_N[19]}]
#set_property PACKAGE_PIN  AL29 [get_ports {CTRLBUS_N_IN}]

set_property PACKAGE_PIN M27 [get_ports {MMCX_U30}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMCX_U30}]

set_property IOSTANDARD LVDS [get_ports {LhcClkInP}]
set_property IOSTANDARD LVDS [get_ports {LhcClkInN}]
set_property PACKAGE_PIN k27 [get_ports {LhcClkInP}] 
#set_property PACKAGE_PIN j27 [get_ports {LhcClkInN}]

create_clock -period 25.000 -waveform {0.000 12.500} [get_ports {LhcClkInP}]


